### ISSUE TITLE
Confused by two places in your code.

### ISSUE THREAD

**Issue by PDFangeltop1** [yuyu2172/chainer-draw#1]
Thank you very much for releasing the code. it helped me a lot.
I read carefully about your code and is confused about two places.

1 In net.py file, on line 152, 
 kl_terms += F.sum(0.5 * (mu_sq + sig_sq - logsig2) - 0.5 * self.n_glimpse, axis=1)
According to the paper, should it be:
 kl_terms += F.sum(0.5 * (mu_sq + sig_sq - logsig2) - 0.5 , axis=1)

2 Still in the net.py file , on line 172.
 x_res_filtered = filter_img(x_res, FY, FY, gamma, self.n_read)
I think it should be:
 x_res_filtered = filter_img(x_res, FX, FY, gamma, self.n_read)

**Comment by yuyu2172** [comment]
Hello.
Thank you for reading my code in such a detail!

I have made errors on the parts of the code you have mentioned.
Thank you for telling me the mistakes.
